apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: microservices-k8s
  name: microservices-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: database-mysql
  namespace: microservices-k8s
spec:
  type: NodePort
  selector:
    app: database-mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30001
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-mysql-pv-volume
  namespace: microservices-k8s
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-mysql-pv-claim
  namespace: microservices-k8s
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-mysql
  namespace: microservices-k8s
spec:
  selector:
    matchLabels:
      app: database-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database-mysql
    spec:
      containers:
      - image: mysql:8.1.0
        name: database-mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: P@ssw0rd
        ports:
        - containerPort: 3306
          name: database-mysql
        volumeMounts:
        - name: database-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: database-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: database-mysql-pv-claim