# -*- mode: ruby -*- 
# vi: set ft=ruby : 

require 'getoptlong'

opts = GetoptLong.new(
	[ '--force', '-f', GetoptLong::NO_ARGUMENT ],
	[ '--provision', '-p', GetoptLong::NO_ARGUMENT ],
	[ '--provision-with', GetoptLong::NO_ARGUMENT ],
	[ '--provider', GetoptLong::OPTIONAL_ARGUMENT ],
	[ '--help', '-h', GetoptLong::NO_ARGUMENT ],
	[ '--check', GetoptLong::NO_ARGUMENT ],
	[ '--logout', GetoptLong::NO_ARGUMENT ],
	[ '--token', GetoptLong::NO_ARGUMENT ],
	[ '--disable-http', GetoptLong::NO_ARGUMENT ],
	[ '--http', GetoptLong::NO_ARGUMENT ],
	[ '--https', GetoptLong::NO_ARGUMENT ],
	[ '--ssh-no-password', GetoptLong::NO_ARGUMENT ],
	[ '--ssh', GetoptLong::NO_ARGUMENT ],
	[ '--ssh-port', GetoptLong::NO_ARGUMENT ],
	[ '--ssh-once', GetoptLong::NO_ARGUMENT ],
	[ '--host', GetoptLong::NO_ARGUMENT ],
	[ '--entry-point', GetoptLong::NO_ARGUMENT ],
	[ '--plugin-source', GetoptLong::NO_ARGUMENT ],
	[ '--plugin-version', GetoptLong::NO_ARGUMENT ],
	[ '--debug', GetoptLong::NO_ARGUMENT ],
	[ '--command', '-c', GetoptLong::NO_ARGUMENT ]
)

node='single'

opts.each do |opt, arg|
	case opt
		when '--help'
			puts <<-EOF
===========================================================================

vagrant [OPTION] <command> [<args>]

-h, --help:
show help

===========================================================================

			EOF
	end
end

ENV['VAGRANT_NO_PARALLEL'] = 'yes' # If this is set, Vagrant will not perform any parallel operations (such as parallel box provisioning). All operations will be performed in serial.

Vagrant.configure(2) do |config| 

	config.vm.define "jasonlws-nexus" do |nexus| 

		nexus.vm.provision "shell", path: "config/nexus-provision.sh"

		nexus.vm.hostname="jasonlws-nexus" 

		nexus.vm.box = "generic/ubuntu2004" 

		nexus.vm.network "private_network", ip: "192.168.56.100", netmask: "255.255.255.0"
	
		nexus.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh" #ssh
		nexus.vm.network "forwarded_port", guest: 8081, host: 18081, id: "nexus-gui" #nexus-gui
		nexus.vm.network "forwarded_port", guest: 5000, host: 15000, id: "docker-group" #docker-group

		nexus.vm.box_check_update = false 
	
		nexus.vm.synced_folder ".\\shared\\nexus", "/root/nexus"
		
		nexus.vm.provider :virtualbox do |v| 

			v.name = "jasonlws-nexus" 
			v.memory = 4096 # 4GB 
			v.cpus = 4

		end 

	end 

end 