# -*- mode: ruby -*- 
# vi: set ft=ruby : 

ENV['VAGRANT_NO_PARALLEL'] = 'yes' 

Vagrant.configure(2) do |config| 

	config.vm.provision "shell", path: "config/ubuntu2004-microk8s-provision.sh"
	
	config.vm.define "jasonlws-microk8s" do |node| 

		node.vm.hostname="jasonlws-microk8s.com" 

		node.vm.box = "generic/ubuntu2004" 

		node.vm.network "private_network", ip: "192.168.56.100", netmask: "255.255.255.0"
	
		node.vm.network "forwarded_port", guest: 31625, host: 31625, id: 'kubernetes-dashboard' #kubernetes-dashboard

		node.vm.box_check_update = false 
	
		node.vm.synced_folder ".\\shared\\jasonlws-microk8s", "/root/jasonlws-microk8s"
		
		node.vm.provider :virtualbox do |v| 

			v.name = "jasonlws-microk8s" 
			v.memory = 8192 # 8GB 
			v.cpus = 4 

		end 

	end 

end 